{"name": "Realizar busca", "status": "failed", "statusDetails": {"message": "AssertionError: 'Get Started' != 'Search Python.org'\n- Get Started\n+ Search Python.org\n\n", "trace": "  File \"c:\\users\\diego\\pycharmprojects\\apresentacao\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\diego\\pycharmprojects\\apresentacao\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\busca_steps.py\", line 28, in step_impl\n    assert_equal(results_page.get_text_title(), 'Search Python.org')\n  File \"C:\\Users\\diego\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\unittest\\case.py\", line 852, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"C:\\Users\\diego\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\unittest\\case.py\", line 1233, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\diego\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\unittest\\case.py\", line 693, in fail\n    raise self.failureException(msg)\n"}, "steps": [{"name": "Dado que acesso o site do Python", "status": "passed", "start": 1602103241862, "stop": 1602103243929}, {"name": "E preencho o input de pesquisa", "status": "passed", "start": 1602103243930, "stop": 1602103244371}, {"name": "Quando clico no botão de pesquisar", "status": "passed", "start": 1602103244371, "stop": 1602103244484}, {"name": "Então devo visualizar os resultados da pesquisa", "status": "failed", "statusDetails": {"message": "AssertionError: 'Get Started' != 'Search Python.org'\n- Get Started\n+ Search Python.org\n\n", "trace": "  File \"c:\\users\\diego\\pycharmprojects\\apresentacao\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\diego\\pycharmprojects\\apresentacao\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\busca_steps.py\", line 28, in step_impl\n    assert_equal(results_page.get_text_title(), 'Search Python.org')\n  File \"C:\\Users\\diego\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\unittest\\case.py\", line 852, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"C:\\Users\\diego\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\unittest\\case.py\", line 1233, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\diego\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\unittest\\case.py\", line 693, in fail\n    raise self.failureException(msg)\n"}, "start": 1602103244484, "stop": 1602103244764}], "start": 1602103241862, "stop": 1602103244765, "uuid": "8f9dc4b9-d4cf-44ac-a8cd-ffc85ab69586", "historyId": "895d41ff3891ed1409fdefb5970cc79b", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "busca"}, {"name": "feature", "value": "fluxo de busca"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}